### ISSUE TITLE
Icon feature in Item-Search

### ISSUE THREAD

**Issue by Kleiduko** [eljoey/BDO-Api-Helper#17]
Hello, i want to create an application with your api. 
I created an Marketplace with your api, but i miss icons, can you add these [here](https://github.com/eljoey/BDO-Api-Helper/blob/master/docs/mpClone/itemSearch.md) ?

**Comment by eljoey** [comment]
Seems like I should be able to throw a link to the .png.  I'll throw something up real quick.

**Comment by eljoey** [comment]
@Kleiduko It's up and running for just that route.  I could probably add it api wide, but it'll take me a few to decide how I'd want to do that.

**Comment by Kleiduko** [comment]
Sorry that i anwere so late, thank you very much
