### ISSUE TITLE
Item bulk search

### ISSUE THREAD

**Issue by Kleiduko** [eljoey/BDO-Api-Helper#18]
Hey, i want to ask you how many items are available to request in one call.

**Comment by eljoey** [comment]
You can request as many as you want in one call, but it's set up to only have 50 requests out at a time.  The more items in a request the longer the response time will be.

**Comment by Kleiduko** [comment]
Thanks, i think by 10 it will be fine ?

**Comment by eljoey** [comment]
That'll be fine
