### ISSUE TITLE
Icon in Item-Search

### ISSUE THREAD

**Issue by Kleiduko** [eljoey/BDO-Api-Helper#19]
Hello, i hope it is okay that i ask this again, can you add icons to [this](https://github.com/eljoey/BDO-Api-Helper/blob/master/docs/itemSearch.md) and [this](https://github.com/eljoey/BDO-Api-Helper/blob/master/docs/search.md) ?
I am very thankfull to you when you can do this.

**Comment by eljoey** [comment]
Should be able to.  I'll go add now

**Comment by eljoey** [comment]
Should be up.  Let me know if you see any issues
