### ISSUE TITLE
Custom Search not working

### ISSUE THREAD

**Issue by SethForrest** [eljoey/BDO-Api-Helper#2]
This could just me being a noob and not making the request properly, but it seems that the bulk-search request isn't working properly.

Here is the script I have been using to demo it:

```python

    import requests
    import json

    payload = {"ids": [9408, 9452]}
    url = 'https://bdo-api-helper.herokuapp.com/api/search?region=na'

    response = requests.request('GET', url, data=payload)
    out = json.loads(response.text)
    print(out)
```

I have successfully been able to make single-item requests to the API, as well as getting the bulk cooking items list.

**Comment by SethForrest** [comment]
Also, is there a way of getting a complete cooking list? I noticed the one provided by `GET /api/prices/cooking` has things like Borscht (9408), but not Fragrant Borscht(9452)?

If this is intentional I will just build a custom search for all the upgraded dishes (provided I can get them working 😄 )

This project is great! Thanks for putting this together!

**Comment by eljoey** [comment]
It should work.  I'm assuming you're using python and requests, I put what
my postman spits out for using that down below. As far as the cooking, I
just manually put in stuff and can add those two items for you. But you're
probably better off creating your own custom one as I will not keep it
updated much at all.  If there's anything else you need let me know.













*import requestsurl =
"https://bdo-api-helper.herokuapp.com/api/search?region=na
<https://bdo-api-helper.herokuapp.com/api/search?region=na>"payload="{\n
 \"ids\": [9408, 9452]\n}"headers = {  'Content-Type':
'application/json'}response = requests.request("GET", url, headers=headers,
data=payload)print(response.text)*

**Comment by eljoey** [comment]
It should work.  I'm assuming you're using python and requests, I put what my postman spits out for using that down below. As far as the cooking, I just manually put in stuff and can add those two items for you. But you're probably better off creating your own custom one as I will not keep it updated much at all.  If there's anything else you need let me know.

```
import requests

url = "https://bdo-api-helper.herokuapp.com/api/search?region=na"

payload="{\n    \"ids\": [9408, 9452]\n}"
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

**Comment by SethForrest** [comment]
Thanks for the quick reply Joe! 
I was just not escaping my quotes on my payload. 

Thanks and keep up the good work!
