### ISSUE TITLE
Market item model

### ISSUE THREAD

**Issue by Kleiduko** [eljoey/BDO-Api-Helper#21]
Good mornig, 

is it possible to make the item results from the api the same format ? 
I think this make it easier to understand and currently i for each api call diffrent models.

Somthing like:
name
id
enhancedGrade
itemGrade
icon
price
count
totalTrades

This is only an idea.

**Comment by eljoey** [comment]
I'm going to be busy for a couple weeks, but I believe all the responses are basically what bdo api gives.

**Comment by Kleiduko** [comment]
Ah okay, then it is fine
