### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Kleiduko** [eljoey/BDO-Api-Helper#24]
Hello, 

is it possible to support more languages ?

**Comment by eljoey** [comment]
Looks like there is Dutch, French, and Spanish.  Shouldn't have to change much to add if you want one of those.

**Comment by Kleiduko** [comment]
Then you don't have to do the work because I need German

**Comment by eljoey** [comment]
So apparently it is German, I just thought it was dutch because of how it was spelled.  I should be able to add it in a bit.

**Comment by eljoey** [comment]
@Kleiduko Lang support has been added. You can add a 'lang' query to your route and set it as 'de'.

ex.
```
bdo-api-helper.herokuapp.com/api/item-search/705510?enhLevel=0&region=eu&lang=de
```

will return: 

```JSON
{
    "name": "Ohrring: Manos",
    "id": 705510,
    "price": 187000000,
    "count": 35,
    "enhanceGrade": 0,
    "totalTrades": 176688,
    "icon": "https://s1.pearlcdn.com/NAEU/TradeMarket/Common/img/BDO/item/705510.png",
    "grade": 4
}
```

**Comment by Kleiduko** [comment]
Thanks to you
